base:
  project_name: cicd
  target: quality

load_dataset:
  bucket: datasetbucket
  filename: WineQT.csv
  raw_data: /data/raw

make_dataset:
  test_split: 0.25
  seed: 41
  processed_data: /data/interim
  res_seed: 42

build_features:
  processed_data: /data/processed

mlflow_config:
  trainingExpName: 'Trained Models'
  tunningExpName: 'Tunned Models'
  bestModelExpName: 'Best Models' 
  remote_server_uri: http://localhost:5000
  mlflow_tracking_uri: mysql+pymysql://admin:Admin123@mysqldb.chqgugyi6uuj.us-east-1.rds.amazonaws.com:3306/mysql_mlflow
  reg_model_name: 'Outperforming Models'
  stage: production
  # cmd to activate server: mlflow server -h 127.0.0.1 -p 5000 --backend-store-uri mysql+pymysql://admin:Admin123@mysqldb.chqgugyi6uuj.us-east-1.rds.amazonaws.com:3306/mysql_mlflow --default-artifact-root s3://mymlflowartifacts/cicdMLflowArtifacts

train_model:
  n_estimators: 100
  criterion: gini
  max_depth: 18
  min_samples_leaf: 30
  random_state: 42
  min_samples_split: 60
  model_dir: /models

hyperopt:
  max_eval: 10
  model_name: best_model